#!/usr/bin/env bash
# First-run setup for the Nexus Framework Compose client on Linux.
# Installs JDK 26, Git, and basic build tools via the system package manager.
# Gradle uses the repo wrapper — root is not required for ./gradlew after this step.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${SETUP_ROOT}/env.sh"

detect_distro() {
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    source /etc/os-release
    local id_like="${ID_LIKE:-}"
    case "${ID:-unknown}" in
      arch|manjaro|endeavouros|garuda)
        echo arch
        ;;
      debian|ubuntu|linuxmint|pop|elementary|zorin)
        echo debian
        ;;
      fedora|rhel|centos|rocky|almalinux|ol)
        echo fedora
        ;;
      *)
        if [[ "$id_like" == *arch* ]]; then
          echo arch
        elif [[ "$id_like" == *debian* ]] || [[ "$id_like" == *ubuntu* ]]; then
          echo debian
        elif [[ "$id_like" == *fedora* ]] || [[ "$id_like" == *rhel* ]]; then
          echo fedora
        else
          echo unknown
        fi
        ;;
    esac
  else
    echo unknown
  fi
}

find_java_home() {
  if command -v java >/dev/null 2>&1; then
    local version
    version="$(java -version 2>&1 | head -n1 || true)"
    if [[ "$version" == *"26"* ]]; then
      if command -v dirname >/dev/null 2>&1 && command -v readlink >/dev/null 2>&1; then
        local java_bin
        java_bin="$(readlink -f "$(command -v java)" 2>/dev/null || true)"
        if [[ -n "$java_bin" ]]; then
          echo "$(dirname "$(dirname "$java_bin")")"
          return 0
        fi
      fi
    fi
  fi

  local candidates=(
    /usr/lib/jvm/java-26-openjdk
    /usr/lib/jvm/java-26-openjdk-amd64
    /usr/lib/jvm/java-26-openjdk-arm64
    /usr/lib/jvm/java-26-openjdk-aarch64
    /usr/lib/jvm/default-java
    /usr/lib/jvm/java-openjdk
  )
  for candidate in "${candidates[@]}"; do
    if [[ -x "${candidate}/bin/java" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

write_env_file() {
  local java_home="$1"
  cat >"$ENV_FILE" <<EOF
# Generated by client-setup/linux/setup.sh — source before ./gradlew :app:run
#   source client-setup/env.sh

export JAVA_HOME="${java_home}"
export PATH="\${JAVA_HOME}/bin:\${PATH}"

# Optional: CMake/Ninja for generated C++ template builds only (not required for the Compose client).
# export CMAKE_GENERATOR=Ninja
EOF
  echo "Wrote ${ENV_FILE}"
}

main() {
  local distro
  distro="$(detect_distro)"
  echo "Detected Linux distro family: ${distro}"

  case "$distro" in
    arch)
      bash "${SCRIPT_DIR}/setup-arch.sh"
      ;;
    debian)
      bash "${SCRIPT_DIR}/setup-debian.sh"
      ;;
    fedora)
      bash "${SCRIPT_DIR}/setup-fedora.sh"
      ;;
    *)
      echo "Unsupported or unknown distro. Install manually:" >&2
      echo "  - OpenJDK 26 (JDK, not JRE)" >&2
      echo "  - Git" >&2
      echo "  - gcc/g++ and make (build-essential on Debian)" >&2
      echo "Then re-run this script to generate client-setup/env.sh, or set JAVA_HOME yourself." >&2
      exit 1
      ;;
  esac

  if ! command -v java >/dev/null 2>&1; then
    echo "error: java not found after package install." >&2
    exit 1
  fi

  local java_home
  if ! java_home="$(find_java_home)"; then
    echo "warning: could not auto-detect JAVA_HOME. Set it manually in ${ENV_FILE}." >&2
    java_home="/usr/lib/jvm/java-26-openjdk"
  fi

  write_env_file "$java_home"

  echo ""
  echo "Next steps:"
  echo "  source client-setup/env.sh"
  echo "  ./gradlew :app:run"
  echo ""
  echo "Gradle wrapper needs no root. CMake/Ninja are optional (template C++ builds only)."
}

main "$@"
