package com.nexus.plotter

/**
 * Native entry point generated by Djinni. The C++ side installs the given
 * PythonBridge so the native PlotController can evaluate functions through
 * Chaquopy.
 */
object PlotterCore {
    external fun installPythonBridge(bridge: PythonBridge)

    init {
        // The generator substitutes {{projectName}} to match the CMake target.
        System.loadLibrary("{{projectName}}")
    }
}
