// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
#include "NativePythonBridge.hpp"

#include "../cpp/plotter_core.hpp"

#include <vector>

namespace nxs::bridge::jni {
namespace {

std::vector<double> toVector(JNIEnv* env, jobject list) {
    jclass listCls = env->GetObjectClass(list);
    jmethodID sizeId = env->GetMethodID(listCls, "size", "()I");
    jmethodID getId = env->GetMethodID(listCls, "get", "(I)Ljava/lang/Object;");
    jclass doubleCls = env->FindClass("java/lang/Double");
    jmethodID doubleValueId = env->GetMethodID(doubleCls, "doubleValue", "()D");

    jint n = env->CallIntMethod(list, sizeId);
    std::vector<double> out(static_cast<std::size_t>(n));
    for (jint i = 0; i < n; ++i) {
        jobject boxed = env->CallObjectMethod(list, getId, i);
        out[static_cast<std::size_t>(i)] = env->CallDoubleMethod(boxed, doubleValueId);
        env->DeleteLocalRef(boxed);
    }
    return out;
}

}  // namespace

NativePythonBridge::NativePythonBridge(JNIEnv* env, jobject javaBridge) {
    env->GetJavaVM(&m_vm);
    m_javaBridge = env->NewGlobalRef(javaBridge);
    jclass cls = env->GetObjectClass(javaBridge);
    m_evaluate = env->GetMethodID(cls, "evaluate",
                                  "(Ljava/lang/String;DDI)Lcom/nexus/plotter/EvalResult;");
}

NativePythonBridge::~NativePythonBridge() {
    JNIEnv* env = nullptr;
    if (m_vm && m_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) == JNI_OK) {
        env->DeleteGlobalRef(m_javaBridge);
    }
}

EvalResult NativePythonBridge::evaluate(const std::string& function_name, double x_min, double x_max,
                                        int32_t samples) {
    JNIEnv* env = nullptr;
    m_vm->AttachCurrentThread(&env, nullptr);

    jstring jName = env->NewStringUTF(function_name.c_str());
    jobject jResult = env->CallObjectMethod(m_javaBridge, m_evaluate, jName, x_min, x_max, samples);
    env->DeleteLocalRef(jName);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return EvalResult{false, "Java exception in PythonBridge.evaluate", {}, {}};
    }

    jclass resultCls = env->GetObjectClass(jResult);
    jboolean ok = env->CallBooleanMethod(jResult, env->GetMethodID(resultCls, "getOk", "()Z"));
    auto jError = static_cast<jstring>(
        env->CallObjectMethod(jResult, env->GetMethodID(resultCls, "getError", "()Ljava/lang/String;")));
    jobject jXs = env->CallObjectMethod(
        jResult, env->GetMethodID(resultCls, "getXs", "()Ljava/util/ArrayList;"));
    jobject jYs = env->CallObjectMethod(
        jResult, env->GetMethodID(resultCls, "getYs", "()Ljava/util/ArrayList;"));

    const char* errChars = env->GetStringUTFChars(jError, nullptr);
    std::string error(errChars);
    env->ReleaseStringUTFChars(jError, errChars);

    return EvalResult{ok == JNI_TRUE, std::move(error), toVector(env, jXs), toVector(env, jYs)};
}

}  // namespace nxs::bridge::jni

extern "C" JNIEXPORT void JNICALL
Java_com_nexus_plotter_PlotterCore_installPythonBridge(JNIEnv* env, jclass, jobject bridge) {
    nxs::bridge::PlotterCore::install_python_bridge(
        std::make_shared<nxs::bridge::jni::NativePythonBridge>(env, bridge));
}
