// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
//
// JNI proxy: wraps a Kotlin PythonBridge object so C++ code can call it
// through the nxs::bridge::PythonBridge interface. Marshals the
// list<f64> record fields to std::vector<double> on each call.
#pragma once

#include "../cpp/python_bridge.hpp"

#include <jni.h>

#include <memory>

namespace nxs::bridge::jni {

class NativePythonBridge final : public PythonBridge {
public:
    NativePythonBridge(JNIEnv* env, jobject kotlinBridge);
    ~NativePythonBridge() override;

    EvalResult evaluate(const std::string& function_name, double x_min, double x_max,
                        int32_t samples) override;

private:
    JavaVM* m_vm = nullptr;
    jobject m_kotlinBridge = nullptr;  // global ref, released in the destructor
    jmethodID m_evaluate = nullptr;
};

// Registered as Java_com_nexus_plotter_PlotterCore_installPythonBridge in
// NativePythonBridge.cpp; forwards to PlotterCore::install_python_bridge.

}  // namespace nxs::bridge::jni
