// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
package com.nexus.plotter;

import java.util.ArrayList;

public final class EvalResult {
    final boolean mOk;
    final String mError;
    final ArrayList<Double> mXs;
    final ArrayList<Double> mYs;

    public EvalResult(boolean ok, String error, ArrayList<Double> xs, ArrayList<Double> ys) {
        this.mOk = ok;
        this.mError = error;
        this.mXs = xs;
        this.mYs = ys;
    }

    public boolean getOk() { return mOk; }
    public String getError() { return mError; }
    public ArrayList<Double> getXs() { return mXs; }
    public ArrayList<Double> getYs() { return mYs; }
}
