// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
package com.nexus.plotter;

public abstract class PlotterCore {
    /** Hands the Chaquopy-backed bridge to the native core before SDL_main runs. */
    public static native void installPythonBridge(PythonBridge bridge);
}
