// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
package com.nexus.plotter;

/** Implemented in Kotlin on top of Chaquopy (see ChaquopyPythonBridge.kt). */
public abstract class PythonBridge {
    public abstract EvalResult evaluate(String functionName, double xMin, double xMax, int samples);
}
