// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
// Regenerate via: scripts/regen-djinni.sh (see template/android-app/README.md)
package com.nexus.plotter

import java.util.ArrayList

/** Result of one Python evaluation. Arrays cross JNI once per resample. */
data class EvalResult(
    val ok: Boolean,
    val error: String,
    val xs: ArrayList<Double>,
    val ys: ArrayList<Double>,
)
