// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
// Regenerate via: scripts/regen-djinni.sh (see template/android-app/README.md)
package com.nexus.plotter

/** Hands the Chaquopy-backed bridge to the native core before SDL_main runs. */
object PlotterCore {
    init {
        // The generator substitutes {{projectName}} to match the CMake target.
        System.loadLibrary("{{projectName}}")
    }

    @JvmStatic
    external fun installPythonBridge(bridge: PythonBridge)
}
