// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
// Regenerate via: scripts/regen-djinni.sh (see template/android-app/README.md)
package com.nexus.plotter

/** Implemented in Kotlin on top of Chaquopy (see ChaquopyPythonBridge.kt). */
abstract class PythonBridge {
    abstract fun evaluate(
        functionName: String,
        xMin: Double,
        xMax: Double,
        samples: Int,
    ): EvalResult
}
