#!/usr/bin/env bash
# First-run setup for the Nexus Framework Compose client on macOS (Homebrew).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${SETUP_ROOT}/env.sh"

if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is required. Install from https://brew.sh then re-run this script." >&2
  exit 1
fi

echo "==> macOS: installing Git and JDK 26..."
brew update
brew install git

if brew list --formula openjdk@26 >/dev/null 2>&1; then
  echo "openjdk@26 already installed."
elif brew list --cask temurin@26 >/dev/null 2>&1; then
  echo "temurin@26 already installed."
else
  if brew info --formula openjdk@26 >/dev/null 2>&1; then
    brew install openjdk@26
  elif brew info --cask temurin@26 >/dev/null 2>&1; then
    brew install --cask temurin@26
  else
    echo "Could not find openjdk@26 or temurin@26 in Homebrew." >&2
    echo "Install JDK 26 manually, then re-run to generate misc/client-setup/env.sh." >&2
    exit 1
  fi
fi

find_java_home() {
  local candidates=()
  if [[ -d "$(brew --prefix openjdk@26 2>/dev/null)/libexec/openjdk.jdk/Contents/Home" ]]; then
    candidates+=("$(brew --prefix openjdk@26)/libexec/openjdk.jdk/Contents/Home")
  fi
  if [[ -d "/Library/Java/JavaVirtualMachines/temurin-26.jdk/Contents/Home" ]]; then
    candidates+=("/Library/Java/JavaVirtualMachines/temurin-26.jdk/Contents/Home")
  fi
  if command -v /usr/libexec/java_home >/dev/null 2>&1; then
    local detected
    detected="$(/usr/libexec/java_home -v 26 2>/dev/null || true)"
    if [[ -n "$detected" ]]; then
      candidates+=("$detected")
    fi
  fi

  for candidate in "${candidates[@]}"; do
    if [[ -x "${candidate}/bin/java" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

java_home=""
if ! java_home="$(find_java_home)"; then
  echo "warning: could not detect JAVA_HOME. Edit ${ENV_FILE} after install." >&2
  java_home="$(brew --prefix openjdk@26 2>/dev/null)/libexec/openjdk.jdk/Contents/Home"
fi

cat >"$ENV_FILE" <<EOF
# Generated by misc/client-setup/macos/setup.sh — source before ./gradlew :app:run
#   source misc/client-setup/env.sh

export JAVA_HOME="${java_home}"
export PATH="\${JAVA_HOME}/bin:\${PATH}"

# Homebrew openjdk@26 (optional symlink hint — not required for Gradle):
#   sudo ln -sfn "\${JAVA_HOME}" /Library/Java/JavaVirtualMachines/openjdk-26.jdk

# Add to ~/.zshrc or ~/.bash_profile for persistence:
#   export JAVA_HOME="${java_home}"
#   export PATH="\${JAVA_HOME}/bin:\${PATH}"
EOF

echo "Wrote ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  source misc/client-setup/env.sh"
echo "  ./gradlew :app:run"
