// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from app.djinni
package com.nexus.{{packageName}}

/** Hands the Chaquopy-backed bridge to the native core before SDL_main runs. */
object AppCore {
    init {
        System.loadLibrary("{{projectName}}")
    }

    @JvmStatic
    external fun installPythonBridge(bridge: PythonBridge)
}
