// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from app.djinni
package com.nexus.{{packageName}}

data class EvalResult(
    val ok: Boolean,
    val error: String,
    val xs: ArrayList<Double>,
    val ys: ArrayList<Double>,
)
