// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from app.djinni
package com.nexus.{{packageName}}

/** Implemented in Kotlin on top of Chaquopy (see ChaquopyPythonBridge.kt). */
abstract class PythonBridge {
    abstract fun greeting(name: String): String

    abstract fun evaluate(
        functionName: String,
        xMin: Double,
        xMax: Double,
        samples: Int,
    ): EvalResult
}
