@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM First-run setup for the Nexus Framework Compose client on Windows.
REM Checks JDK 26 and Git; prints install hints (winget/chocolatey). Generates client-setup\env.bat.

set "SCRIPT_DIR=%~dp0"
set "SETUP_ROOT=%SCRIPT_DIR%.."
set "ENV_FILE=%SETUP_ROOT%env.bat"

echo ==^> Nexus Framework client setup (Windows)
echo.

set "JAVA_OK=0"
set "GIT_OK=0"
set "JAVA_HOME_DETECTED="

where java >nul 2>&1
if %ERRORLEVEL% equ 0 (
  for /f "tokens=*" %%v in ('java -version 2^>^&1 ^| findstr /i "version"') do set "JAVA_VER=%%v"
  echo Found: !JAVA_VER!
  echo !JAVA_VER! | findstr /i "26" >nul
  if !ERRORLEVEL! equ 0 set "JAVA_OK=1"
)

if "!JAVA_OK!"=="0" (
  echo.
  echo JDK 26 not detected. Install OpenJDK 26, then re-run this script.
  echo.
  echo winget ^(recommended^):
  echo   winget install Microsoft.OpenJDK.26
  echo   winget install EclipseAdoptium.Temurin.26.JDK
  echo.
  echo Chocolatey:
  echo   choco install temurin26
  echo.
)

where git >nul 2>&1
if %ERRORLEVEL% equ 0 (
  set "GIT_OK=1"
  for /f "tokens=*" %%g in ('git --version') do echo Found: %%g
) else (
  echo Git not found.
  echo   winget install Git.Git
  echo   choco install git
  echo.
)

if "!JAVA_OK!"=="1" (
  if defined JAVA_HOME (
    set "JAVA_HOME_DETECTED=!JAVA_HOME!"
  ) else (
    for /f "tokens=*" %%j in ('where java 2^>nul') do (
      set "JAVA_BIN=%%j"
      goto :found_java
    )
    :found_java
    if defined JAVA_BIN (
      for %%I in ("!JAVA_BIN!") do set "JAVA_HOME_DETECTED=%%~dpI.."
    )
  )
)

(
  echo @echo off
  echo REM Generated by client-setup\windows\setup.bat — run before gradlew.bat :app:run
  echo REM   call client-setup\env.bat
  echo.
  if defined JAVA_HOME_DETECTED (
    echo set "JAVA_HOME=!JAVA_HOME_DETECTED!"
  ) else (
    echo REM Set JAVA_HOME to your JDK 26 install, e.g.:
    echo REM set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-26"
    echo set "JAVA_HOME=C:\Program Files\Microsoft\jdk-26"
  )
  echo set "PATH=%%JAVA_HOME%%\bin;%%PATH%%"
) > "%ENV_FILE%"

echo.
echo Wrote %ENV_FILE%
echo.
echo Next steps:
echo   call client-setup\env.bat
echo   gradlew.bat :app:run
echo.
echo Gradle wrapper needs no admin. CMake/Ninja are optional ^(template C++ builds only^).

if "!JAVA_OK!"=="0" exit /b 1
if "!GIT_OK!"=="0" exit /b 1
exit /b 0
