// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from app.djinni
#pragma once

#include <memory>

namespace nxs::bridge {

class PythonBridge;

class AppCore {
public:
    virtual ~AppCore() = default;

    static void install_python_bridge(const std::shared_ptr<PythonBridge>& bridge);
};

}  // namespace nxs::bridge
