// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
#pragma once

#include <memory>

namespace nxs::bridge {

class PythonBridge;

// Implemented in C++ (interface +c). Definition lives in
// src/controller/PythonEngine.cpp (PlotterCore::install_python_bridge).
class PlotterCore {
public:
    virtual ~PlotterCore() = default;

    static void install_python_bridge(const std::shared_ptr<PythonBridge>& bridge);
};

}  // namespace nxs::bridge
