// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from plotter.djinni
#pragma once

#include "eval_result.hpp"

#include <cstdint>
#include <string>

namespace nxs::bridge {

// Implemented on the Kotlin/JVM side (interface +j): calls Chaquopy's
// CPython and returns the sampled arrays across JNI once per resample.
class PythonBridge {
public:
    virtual ~PythonBridge() = default;

    virtual EvalResult evaluate(const std::string& function_name, double x_min, double x_max,
                                int32_t samples) = 0;
};

}  // namespace nxs::bridge
