// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from app.djinni
#pragma once

#include "eval_result.hpp"

#include <cstdint>
#include <string>

namespace nxs::bridge {

class PythonBridge {
public:
    virtual ~PythonBridge() = default;

    virtual std::string greeting(const std::string& name) = 0;

    virtual EvalResult evaluate(const std::string& function_name, double x_min, double x_max,
                                int32_t samples) = 0;
};

}  // namespace nxs::bridge
